[interface]
mode = "connector"
private_key = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgDNorbM0jjhKwSaZi6za/gw+OOhCfwpsmRB/uefzmC1WhRANCAASq+U/iJueOg/Kw4rbJlISiorjFHqExkRfTKF/6fEyGEIfNsx114aSV4WYSflLyHuuxi3WEqehDHoYs5kjEmCrt"
address = "10.0.0.3/24"
max_idle_timeout_ms = 600000
cipher = "aes-128-gcm"

[engine]
cc = "none"
recv_buf = 2097152
send_buf = 2097152
offload = true
batch_size = 256

[peer]
public_key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDN8+4EyG/w8nChort+zSPlnCS5QcoFR8W/Om6HsF3ZIsimoSeiQnK0fKCFH9V7rw/P6KUJXcOkUJnuJpRhooPg=="
endpoint = "10.23.30.100:4433"
allowed_ips = ["10.0.0.0/24"]
keepalive = 25
